<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>eecac45f-74de-4d4a-891a-7bdd8c37b68b</UserSecretsId>
		<!--<SpaRoot>..\Frontend\</SpaRoot>-->
		<!--<SpaProxyServerUrl>http://localhost:5173</SpaProxyServerUrl>-->
		<!--<SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>-->
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.26" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.9" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Google" Version="1.77.0-alpha" />
    <PackageReference Include="Polly" Version="8.7.0" />
    <PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
	</ItemGroup>


	<Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <Exec Command="npm install" WorkingDirectory="..\Frontend" />
    <Exec Command="npm run build" WorkingDirectory="..\Frontend" />
    <ItemGroup>
        <DistFiles Include="../../Frontend/dist/**/*.*" />
        <ResolvedFileToPublish Include="@(DistFiles)">
            <RelativePath>wwwroot/%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </ResolvedFileToPublish>
    </ItemGroup>
</Target>

</Project>
